import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
    return [
        { url: 'https://lmnas.com/en', lastModified: new Date() },
        { url: 'https://lmnas.com/de', lastModified: new Date() },
        { url: 'https://lmnas.com/en/products/lens-erp-suite', lastModified: new Date() },
        { url: 'https://lmnas.com/de/products/lens-erp-suite', lastModified: new Date() },
        { url: 'https://lmnas.com/en/products/crm-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/de/products/crm-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/en/products/analytical-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/de/products/analytical-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/en/products/cpq-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/de/products/cpq-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/en/products/hrms-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/de/products/hrms-cloud', lastModified: new Date() },
        { url: 'https://lmnas.com/en/products/lumi', lastModified: new Date() },
        { url: 'https://lmnas.com/de/products/lumi', lastModified: new Date() },
        { url: 'https://lmnas.com/en/industries/manufacturing', lastModified: new Date() },
        { url: 'https://lmnas.com/de/industries/manufacturing', lastModified: new Date() },
        { url: 'https://lmnas.com/en/industries/distribution', lastModified: new Date() },
        { url: 'https://lmnas.com/de/industries/distribution', lastModified: new Date() },
        { url: 'https://lmnas.com/en/industries/retail', lastModified: new Date() },
        { url: 'https://lmnas.com/de/industries/retail', lastModified: new Date() },
        { url: 'https://lmnas.com/en/solutions', lastModified: new Date() },
        { url: 'https://lmnas.com/de/solutions', lastModified: new Date() },
        { url: 'https://lmnas.com/en/pricing', lastModified: new Date() },
        { url: 'https://lmnas.com/de/pricing', lastModified: new Date() },
        { url: 'https://lmnas.com/en/about-us', lastModified: new Date() },
        { url: 'https://lmnas.com/de/about-us', lastModified: new Date() },
        { url: 'https://lmnas.com/en/blog', lastModified: new Date() },
        { url: 'https://lmnas.com/de/blog', lastModified: new Date() },
        { url: 'https://lmnas.com/en/career', lastModified: new Date() },
        { url: 'https://lmnas.com/de/career', lastModified: new Date() },
        { url: 'https://lmnas.com/en/trending-now', lastModified: new Date() },
        { url: 'https://lmnas.com/de/trending-now', lastModified: new Date() },
        { url: 'https://lmnas.com/en/event', lastModified: new Date() },
        { url: 'https://lmnas.com/de/event', lastModified: new Date() },
    ]
}